name: Expense Tracker - Advanced Git Workflow

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup basic environment
        run: echo "Setting up environment for Expense Tracker project."

      - name: Git Log - Auditing Commits
        run: git log --oneline --graph --all

      - name: Conflict Check (example)
        run: echo "No conflict detected. Ready to merge!"

      - name: Done
        run: echo "Build and audit finished!"
